import os
import glob
import FreeCAD as App
import FreeCADGui as Gui

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
BUILD = os.path.join(ROOT, 'build_v50')
OUT = os.path.join(ROOT, 'docs', 'renders')
os.makedirs(OUT, exist_ok=True)

# Deterministic FreeCAD screenshots for GitHub README previews.
# Generated directly from the FCStd files produced by the build.

def set_view(view):
    try:
        view.setAnimationEnabled(False)
    except Exception:
        pass
    try:
        view.setCameraType('Perspective')
    except Exception:
        pass
    view.viewAxonometric()
    view.fitAll(0.80)


def style_doc(doc):
    for obj in doc.Objects:
        if not hasattr(obj, 'ViewObject') or not hasattr(obj, 'Shape'):
            continue
        n = obj.Name.lower()
        try:
            obj.ViewObject.DisplayMode = 'Flat Lines'
        except Exception:
            pass
        try:
            obj.ViewObject.LineWidth = 1.0
        except Exception:
            pass
        if n.startswith('ref_'):
            obj.ViewObject.ShapeColor = (0.72, 0.72, 0.72)
            obj.ViewObject.LineColor = (0.45, 0.45, 0.45)
            obj.ViewObject.Transparency = 65
        elif 'plate' in n:
            obj.ViewObject.ShapeColor = (0.82, 0.55, 0.20)
        elif 'spindle' in n or 'lead_screw' in n:
            obj.ViewObject.ShapeColor = (0.72, 0.72, 0.76)
        elif 'knob' in n:
            obj.ViewObject.ShapeColor = (0.25, 0.25, 0.28)
        elif 'lower' in n:
            obj.ViewObject.ShapeColor = (0.35, 0.38, 0.42)
        else:
            obj.ViewObject.ShapeColor = (0.48, 0.52, 0.56)


def gui_doc_for(doc):
    # FreeCAD 1.1.x AppImage does not expose FreeCADGui.activeDocument().
    # Resolve the GUI document explicitly from the application document name.
    try:
        gdoc = Gui.getDocument(doc.Name)
    except Exception:
        gdoc = None
    if gdoc is None:
        Gui.activateWorkbench('Part')
        gdoc = Gui.getDocument(doc.Name)
    return gdoc


def render_fcstd(path, out_name, width=1000, height=760):
    doc = App.openDocument(path)
    App.setActiveDocument(doc.Name)
    Gui.updateGui()
    gdoc = gui_doc_for(doc)
    view = gdoc.activeView()
    style_doc(doc)
    set_view(view)
    Gui.updateGui()
    out = os.path.join(OUT, out_name)
    ok = view.saveImage(out, width, height, 'Current')
    Gui.updateGui()
    App.closeDocument(doc.Name)
    if not os.path.isfile(out) or os.path.getsize(out) == 0:
        raise RuntimeError('FreeCAD did not create preview: ' + out)
    return out


assembly = os.path.join(BUILD, 'eurobox_v50_assembly.FCStd')
if not os.path.isfile(assembly):
    raise SystemExit('Missing assembly FCStd: ' + assembly)

render_fcstd(assembly, 'v50_assembly.png', width=1400, height=900)

parts = sorted(
    p for p in glob.glob(os.path.join(BUILD, 'eurobox_v50_*.FCStd'))
    if not p.endswith('eurobox_v50_assembly.FCStd')
)
if not parts:
    raise SystemExit('No part FCStd files found in ' + BUILD)

for path in parts:
    stem = os.path.splitext(os.path.basename(path))[0]
    render_fcstd(path, stem + '.png', width=900, height=700)

with open(os.path.join(OUT, 'README.txt'), 'w', encoding='utf-8') as f:
    f.write('Generated by FreeCAD 1.1.3 from build_v50/*.FCStd via scripts/render_v50.py\n')
    f.write('Do not hand-edit these preview images.\n')

print('Rendered', 1 + len(parts), 'FreeCAD previews to', OUT)
